<a href="https://colab.research.google.com/github/prophecied/PortfolioProject/blob/main/pythonDANumpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
a = np.array([1,2,3,4])

In [7]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [ ]:
a[0], a[1]

(1, 2)

In [ ]:
a[0:]

array([1, 2, 3])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [ ]:
b[[0, 2, -1]]

array([0., 1., 2.])

Array Types

In [5]:
a

array([1, 2, 3, 4])

In [6]:
a.dtype

dtype('int64')

In [8]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [9]:
b.dtype

dtype('float64')

In [11]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [12]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [13]:
c = np.array(['a', 'b', 'c'])

In [14]:
c.dtype

dtype('<U1')

In [15]:
d = np.array([{'a': 1}, sys])

In [17]:
d.dtype

dtype('O')

Dimensions and shape

In [18]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [19]:
A.shape

(2, 3)

In [20]:
A.ndim

2

In [21]:
A.size

6

In [22]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 4]

    ]
])

In [23]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  4]]])

In [24]:
B.shape

(2, 2, 3)

In [25]:
B.ndim

3

In [26]:
B.size

12

Indexing and Slicing of Matrices

In [2]:
A = np.array([
#    0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [3]:
A[1]

array([4, 5, 6])

In [4]:
A[1][0]

4

In [5]:
A[1, 0]

4

In [6]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [8]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [9]:
A[:2, 2:]

array([[3],
       [6]])

In [10]:
A[1] = np.array([10, 10, 10])

In [11]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [12]:
A[2] = 99

In [13]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [14]:
a = np.array([1, 2, 3, 4])

In [15]:
a.sum()

10

In [16]:
a.mean()

2.5

In [17]:
a.std()

1.118033988749895

In [18]:
a.var()

1.25

In [19]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [20]:
A.sum()

45

In [21]:
A.mean()

5.0

In [22]:
A.std()

2.581988897471611

In [23]:
A.sum(axis = 1)

array([ 6, 15, 24])

In [24]:
A.mean(axis = 0)

array([4., 5., 6.])

In [25]:
A.mean(axis = 1)

array([2., 5., 8.])

In [26]:
A.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [27]:
A.std(axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

Broadcasting and Vectorized operations

In [28]:
a = np.arange(4)

In [29]:
a

array([0, 1, 2, 3])

In [30]:
a + 10

array([10, 11, 12, 13])

In [31]:
a * 10

array([ 0, 10, 20, 30])

In [32]:
a += 100

In [33]:
a

array([100, 101, 102, 103])

In [34]:
l = [0, 1, 2, 3]

In [35]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [36]:
a = np.arange(4)

In [37]:
b = np.array([10, 10, 10, 10])

In [38]:
a + b

array([10, 11, 12, 13])

In [39]:
a * b

array([ 0, 10, 20, 30])

Boolean arrays

In [4]:
a = np.arange(4)

In [41]:
a

array([0, 1, 2, 3])

In [42]:
a[0] , a[-1]

(0, 3)

In [43]:
a[[0 , -1]]

array([0, 3])

In [5]:
a[[True, False, False, True]]

array([0, 3])

In [6]:
a >=2

array([False, False,  True,  True])

In [7]:
a[a >=2]

array([2, 3])

In [8]:
a.mean()

1.5

In [9]:
a[a > a.mean()]

array([2, 3])

In [11]:
a[~(a > a.mean())]

array([0, 1])

In [12]:
a[(a == 0)| (a == 1)]

array([0, 1])

In [13]:
a[(a <=2) & (a % 2 == 0)]

array([0, 2])

In [16]:
A = np.random.randint(100, size=(3,3))

In [17]:
A

array([[22, 90, 21],
       [45, 56, 74],
       [48, 57, 77]])

In [18]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([22, 21, 56, 48, 77])

In [19]:
A > 30

array([[False,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
A[A > 30]

array([90, 45, 56, 74, 48, 57, 77])

Linear Algebra

In [22]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [23]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [25]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [26]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [27]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [28]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Int, floats

In [29]:
# integer in python is > 24 bytes
sys.getsizeof(1)

28

In [30]:
# longs are longer
sys.getsizeof(10**100)

72

In [31]:
#numpy size is much smaller
np.dtype(int).itemsize

8

In [32]:
np.dtype(np.int8).itemsize

1

In [33]:
np.dtype(float).itemsize

8

In [34]:
sys.getsizeof([1])

64

In [35]:
np.array([1]).nbytes

8

In [36]:
l = list(range(100000))

In [37]:
a = np.arange(100000)

In [38]:
%time np.sum(a**2)

CPU times: user 1.11 ms, sys: 0 ns, total: 1.11 ms
Wall time: 993 µs


333328333350000

In [39]:
%time sum([x**2 for x in l])

CPU times: user 33.8 ms, sys: 2.84 ms, total: 36.6 ms
Wall time: 36.8 ms


333328333350000

Useful numpy funtions


In [40]:
np.random.random(size = 2)

array([0.43433523, 0.45594211])

In [41]:
np.random.normal(size = 2)

array([-0.88795472,  0.12933037])

In [42]:
np.random.rand(2, 4)

array([[0.01609778, 0.61202983, 0.24819827, 0.64958555],
       [0.6380163 , 0.99129635, 0.41833997, 0.00821233]])

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [47]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [48]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [51]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [52]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [53]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [54]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [55]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.zeros((3, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [59]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [61]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [63]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.eye(8,4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
"hello world"[6]

'w'

Numpy Exercise

Create a numpy array of size 10, filled with zeros

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a numpy array with values ranging from 10 to 49


In [7]:
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a numpy matrix of 2*2 integers, filled with ones

In [12]:
np.ones((2,2), dtype = int)

array([[1, 1],
       [1, 1]])

Given the x numpy array, create a new numpy array with the same shape and type as X, filled with ones


In [14]:
X = np.arange(4, dtype = int)
np.ones_like(X)

array([1, 1, 1, 1])

Given the X numpy matrix, create a new nupy matrix with the same shape and type as X filled with zeros

In [17]:
X = np.array([[1,2,3],[4,5,6]], dtype = int)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

Create a numpy matrix of 4*4 integers, filled with fives

In [18]:
np.ones([4,4],dtype = int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, flled with sevens

In [21]:
X = np.array([[2,3],[6,2]], dtype = int)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a numpy array, filled with 3 random integer values between 1 and 10

In [27]:
np.random.randint(10, size =3 )

array([1, 2, 2])

Create a 3*3*3 numpy matrix, filled with random float *values*

In [28]:
np.random.randn(3,3,3)

array([[[ 0.97429211,  0.61876907, -0.13434963],
        [-2.11817362, -0.22464834,  0.7432067 ],
        [ 0.8722804 , -1.87888443, -1.23153001]],

       [[ 0.45909701, -0.76780526, -0.35034886],
        [ 0.61850411,  0.3746951 , -0.36334828],
        [ 0.51440979, -0.11178998,  0.62006367]],

       [[-1.92973603, -1.76330925, -0.52428315],
        [ 0.06067746, -0.26594887, -0.74485137],
        [-1.00133622,  2.49474282, -0.26995857]]])

Given the X python list convert it to an Y numpy array

In [32]:
X = [1,2,3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


Given the X numpy array, make a copy and it on Y

In [35]:
X = np.array([5,2,3], dtype = int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 137259629349744
[5 2 3] 137259629349168


Create a numpy array with numbers from 1 to 10

In [36]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a numpy array with odd number netween 1 to 10

In [40]:
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

Create a numpy array with numbers from 1 to 10, in descending order

In [41]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [42]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Show the memory size of the given Z numpy matrix

In [43]:
Z = np.zeros((10,10))
print("%d bytes"%(Z.size*Z.itemsize))

800 bytes


Given the X numpy array, show its first element

In [2]:
X = np.array(["A", "B", "C", "D", "E"])
X[0]

'A'

Given the X numpy array, show its last element

In [3]:
X = np.array(["A", "B", "C", "D", "E"])
X[-1]

'E'

Given the X numpy arrau show its first three elements

In [4]:
X = np.array(["A", "B", "C", "D", "E"])
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

Given the X numpy arraym show all the middle elements

In [5]:
X = np.array(["A", "B", "C", "D", "E"])
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

Given the X numpy array, show the elements in reverse position

In [7]:
X = np.array(["A", "B", "C", "D", "E"])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

Given the X numpy array, show the elements in an odd position

In [8]:
X = np.array(["A", "B", "C", "D", "E"])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

Givent the X numpy matrix, show the first row elements

In [9]:
X = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15,16]
])
X[0]

array([1, 2, 3, 4])

Given the X numpy matrix, show th elast row elements

In [10]:
X = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15,16]
])
X[-1]

array([13, 14, 15, 16])

Given the X numpy matrix, show the first element on the first row

In [11]:
X = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15,16]
])
X[0,0]

1

Given the X numpy matrix, show the last element on the last row

In [12]:
X = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15,16]
])
X[-1,-1]

16

Given the X numpy matrix, show the middle row elements

In [13]:
X = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15,16]
])
X[1:-1,1:-1]

array([[ 6,  7],
       [10, 11]])

Given the X numpy matrix, show the first two elements on the first two rows

In [14]:
X = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15,16]
])
X[:2,:2]

array([[1, 2],
       [5, 6]])

Given the X numpy matrix, show the last two elements on the last two rows

In [15]:
X = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15,16]
])
X[2:,2:]

array([[11, 12],
       [15, 16]])

Convert the given integer numpy array to float

In [17]:
X = [-5,-3,0,10,40]
np.array(X,float)

array([-5., -3.,  0., 10., 40.])

Reverse the given numpy array

In [18]:
X = [-5,-3,0,10,40]
X[::-1]

[40, 10, 0, -3, -5]

Order the given numpy array


In [20]:
X = [0, 10, -5, 40, -3]
X.sort()
X

[-5, -3, 0, 10, 40]

Given the X numpy array set the fifth element equal 1

In [22]:
X = np.zeros(10)
X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Given the X numpy array, change the 50 with a 40

In [23]:
X = np.array([10, 20, 30, 50])
X[3] = 40
X

array([10, 20, 30, 40])

Given the X numpy matrix change the lst row with all 1

In [25]:
X = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15,16]
])
X[-1] = 1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

Given the X numpy matrix, change the last item on the last row with a 0

In [26]:
X = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15,16]
])
X[-1,-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

Given the X numpy matrix, add 5 to every element

In [28]:
X = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15,16]
])
X + 5


array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

Given the X numpy array make a mask showing the negative elements

In [3]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X<=0
mask

array([-1,  0, -4,  0,  0, -9])

Given the X numpy array, get the negative elements

In [4]:
X  = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = X<=0
X[mask]

array([-1,  0, -4,  0,  0, -9])

Given the X numpy array, get numbers higher than 5

In [5]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = X>5
X[mask]

array([ 6, 10])

Given the X numpy array, get numbers higher than the elements

In [7]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

Given the X numpy array, get numbers equal to 2 or 10


In [8]:
X =np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = (X==2)|(X==10)
X[mask]

array([ 2, 10])

Given the X numpy array, return True if none of its elements is zero

In [9]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.all()

False

Given the X numpy array, return True if any of its elements is zero

In [10]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.any()

True

Given the X numpy array, show the mean value of its elements


In [11]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.mean()

3.7

Given the X numpy matrix show the sum of its columns

In [13]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11,12]
])
X.sum(axis = 0) #axis = 0 columns; axis = 1 rows

array([15, 18, 21, 24])

Given the X numpy matrix show the mean value of its rows

In [14]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11,12]
])
X.mean(axis = 1)

array([ 2.5,  6.5, 10.5])

Given the X numpy array, show the max value of its elements

In [15]:
X = np.array([1, 2, 3, 4, 5, 6, 0, 0, 9, 10])
X.max()

10